# Generated by Django 3.0 on 2022-03-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'ຄະນິດສາດ'), ('sci', 'ວິທະຍາສາດ'), ('art', 'ສິລະປະ'), ('eng', 'ພາສາອັງກີດ'), ('physics', 'ຟີຊີກ'), ('bio', 'ຊິວະ')], default='math', max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
